version: '3'

services:
  angular:
    build:
      angular-client
    ports:
    - "4200:4200"

  nodejs:
    build:
      /
    ports:
    - "5000:5000"

  db:
    image: mongo
    ports:
    - "27017:27017"